# Generated by Django 4.1.5 on 2023-01-17 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacjenci', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specjalizacja',
            name='specjalizacja',
            field=models.CharField(choices=[('Rodzinny', 'Rodzinny')], max_length=30),
        ),
        migrations.AlterField(
            model_name='wizyta',
            name='content',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Notatka',
        ),
    ]
