# Generated by Django 4.1.5 on 2023-01-17 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacjenci', '0002_alter_specjalizacja_specjalizacja_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wizyta',
            old_name='doctor',
            new_name='lekarz',
        ),
    ]
