# Generated by Django 4.1.5 on 2023-01-17 21:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pacjenci', '0003_rename_doctor_wizyta_lekarz'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacjent',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
